# Generated by Django 3.2.25 on 2026-05-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0022_screen_name_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="admin_disabled_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="state_locked",
            field=models.BooleanField(default=False),
        ),
    ]
