# Generated by Django 3.2.25 on 2026-05-19 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0022_screen_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, e.g. +61417123456.', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
    ]
