# Generated by Django 3.2.25 on 2026-05-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    # Renumbered from 0023_*; without this, DBs that recorded the old name
    # re-run the AddFields below and fail on duplicate columns.
    replaces = [
        ("profile", "0023_admin_disabled_access_and_state_locked"),
    ]

    dependencies = [
        ("profile", "0023_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="admin_disabled_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="state_locked",
            field=models.BooleanField(default=False),
        ),
    ]
