# Generated by Django 3.2.25 on 2026-05-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0024_admin_disabled_access_and_state_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
