# Generated by Django 3.2.25 on 2026-08-17 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0025_terms_accepted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="digital_id_token_expire",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
    ]
