# Generated by Django 3.2.25 on 2025-01-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0026_alter_profile_digital_id_token_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="memberdoc_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
