# Generated by Django 3.2.25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0029_migrate_email_backend_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListmonkMemberSyncOutbox",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "desired_state",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=8,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("pending", models.BooleanField(default=True)),
                (
                    "remote_subscriber_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listmonk_sync",
                        to="profile.profile",
                    ),
                ),
            ],
        ),
    ]
