# Generated by Django 6.0.8 on 2026-09-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0029_induction_provider_state"),
        ("profile", "0030_listmonk_member_sync_outbox"),
    ]

    operations = []
