# Generated by Django 6.0.8 on 2026-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0032_induction_provider_external_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inductionproviderstate",
            name="provider",
            field=models.CharField(
                choices=[
                    ("canvas", "Canvas"),
                    ("moodle", "Moodle"),
                    ("docuseal", "DocuSeal"),
                    ("legacy", "Legacy aggregate induction"),
                ],
                max_length=20,
            ),
        ),
    ]
