name: Build Docker Image (On Prod Release)

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "!v[0-9]+.[0-9]+.[0-9]+-*"

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/_build-docker.yml
    permissions:
      contents: read
      packages: write # pushes the built image to GHCR
    with:
      platforms: linux/amd64,linux/arm64
      push: true
      tags: |-
        ghcr.io/pawprintprototyping/membermatters:latest,ghcr.io/pawprintprototyping/membermatters:${{ github.sha }},ghcr.io/pawprintprototyping/membermatters:${{ github.ref_name }}
